### ISSUE TITLE
German catalog

### ISSUE THREAD

**Issue by halle-saale** [emartisoft/AmiWeatherForecasts#10]
Morning Murat.

This is a first draft for a German catalog for your application. Of course I would have tested before but I am not quite sure, how?
I edited the ct file and finally renamed it to AmiWeatherForecasts.catalog. Then I created a drawer "Deutsch" and put it there as well as drawer "Catalogs" --> "Deutsch" and put it there. But it does not work, so I definitely did something wrong....;)

By the way: mail "common" mails obviously did not get you, so let me say here: best wishes from Amiga-News.de! :)
[AmiWeatherForecasts_deutsch.ct.txt](https://github.com/emartisoft/AmiWeatherForecasts/files/14000677/AmiWeatherForecasts_deutsch.ct.txt)

PS: Version 1.6 still is not accessable...

**Comment by emartisoft** [comment]
The translations are okay, but as you said, the file formatting is incorrect. It should be like below. I'll fix it. Thank you

## version $VER: AmiWeatherForecasts.catalog 1.0 (31.12.23)
## language deutsch
;
str_29
Über
; About
;
str_30
Beenden
; Quit
;
str_31
Weather Forecast aktualisieren
; Update Weather Forecast
;
str_32
Datum und Zeit einstellen
; Set Date and Time Manually
;


.....

**Comment by emartisoft** [comment]
> PS: Version 1.6 still is not accessable...

It waits german catalog

**Comment by emartisoft** [comment]
Can you translate for the following?

Get Months
Get Days
Test
Get My Location
Save
Close
Ok
Info
Restore Defaults

**Comment by emartisoft** [comment]
I uploaded german catalog.
