### ISSUE TITLE
encoding problem with french setup

### ISSUE THREAD

**Issue by psypoker** [emartisoft/AmiWeatherForecasts#3]
Hi, the accentued characters are bad rendered from the api to the screen 
instead of [ciel dégagé] i got [ciel d@Agag@A]
when text is converted from api with this function : 
extern char* convertTRChar(char* str);

is there a ovveride to this function to manage encodings ? utf-8 to ANSI (i think)
or to ignore the accentued chars ...

best regards

**Comment by emartisoft** [comment]
Hi,
I implemented this function because I experienced a similar problem with Turkish characters. I don't know French, but if you can tell me which characters may cause problems, I can solve this problem.

for example:
@A -> é

**Comment by psypoker** [comment]
Hi, 
some i had identified at this moment : 
[légère pluie] => [lA©gA¨re pluie] ==> é => A© , è => A¨
[ciel dégagé] => [ciel dA©gagA©] ==> é => A©
more to come  :) 
i need to have a look at the api responses in french
** EDIT **
on Aminet : UniDecode0.13.lha may be usefull for converting the source encoding (utf8/html/url...) to ansi amiga !
(erf no sources, dok in german)
french site with all encoding explained (in french) : https://infoforall.fr/fiches/fiches-act020.html#partie_07

**Comment by emartisoft** [comment]
Hi again,
I fixed this problem for extended ASCII table. You may download executable file only to try it. Thanks.

![encoding1](https://github.com/emartisoft/AmiWeatherForecasts/assets/20000674/7ed9ee92-4d31-475b-a6f8-58cc1d31e9b8)
![encoding2](https://github.com/emartisoft/AmiWeatherForecasts/assets/20000674/cd42a281-35a7-41ee-b4df-1d8b4298711c)


192 | C0 | À |  
193 | C1 | Á |  
194 | C2 | Â |  
195 | C3 | Ã |  
196 | C4 | Ä |  
197 | C5 | Å |  
198 | C6 | Æ |  
199 | C7 | Ç |  
200 | C8 | È |  
201 | C9 | É |  
202 | CA | Ê |  
203 | CB | Ë |  
204 | CC | Ì |  
205 | CD | Í |  
206 | CE | Î |  
207 | CF | Ï |  
208 | D0 | Ð |  
209 | D1 | Ñ |  
210 | D2 | Ò |  
211 | D3 | Ó |  
212 | D4 | Ô |  
213 | D5 | Õ |  
214 | D6 | Ö |  
215 | D7 | × |  
216 | D8 | Ø |  
217 | D9 | Ù |  
218 | DA | Ú |  
219 | DB | Û |  
220 | DC | Ü |  
221 | DD | Ý |  
222 | DE | Þ |  
223 | DF | ß |  
224 | E0 | à |  
225 | E1 | á |  
226 | E2 | â |  
227 | E3 | ã |  
228 | E4 | ä |  
229 | E5 | å |  
230 | E6 | æ |  
231 | E7 | ç |  
232 | E8 | è |  
233 | E9 | é |  
234 | EA | ê |  
235 | EB | ë |  
236 | EC | ì |  
237 | ED | í |  
238 | EE | î |  
239 | EF | ï |  
240 | F0 | ð |  
241 | F1 | ñ |  
242 | F2 | ò |  
243 | F3 | ó |  
244 | F4 | ô |  
245 | F5 | õ |  
246 | F6 | ö |  
247 | F7 | ÷ |  
248 | F8 | ø |  
249 | F9 | ù |  
250 | FA | ú |  
251 | FB | û |  
252 | FC | ü |  
253 | FD | ý |  
254 | FE | þ |  
255 | FF | ÿ |

**Comment by psypoker** [comment]
issue seems to be solved ! nice job
