### ISSUE TITLE
text with date and time cropped

### ISSUE THREAD

**Issue by psypoker** [emartisoft/AmiWeatherForecasts#4]
![screen amigajpg](https://github.com/emartisoft/AmiWeatherForecasts/assets/39156660/fc8d52f1-5231-4ce1-afb8-7e55c35f8268)

date & time is cropped, no matter what is the "add to pos x" value
for info , i'm on a rtg screen, with pistorm on a 500+

**Comment by emartisoft** [comment]
Set a negative value to 'Add to Pos X'. for example: -32

**Comment by psypoker** [comment]
> Set a negative value to 'Add to Pos X'. for example: -32

it does'nt

**Comment by emartisoft** [comment]
I fixed this. Try it for version 1.4.
