### ISSUE TITLE
A few problems...

### ISSUE THREAD

**Issue by Tallguy298** [emartisoft/AmiWeatherForecasts#6]
Problem 1...
Changing the screen-mode preferences causes a pop up window to appear.
![Image1](https://github.com/emartisoft/AmiWeatherForecasts/assets/148932062/afc92875-0998-47aa-8da2-38454c82a9b4)

Problem 2...
Selecting Manual from the menu does not seem to do anything.
I am assuming that it should open the AmigaGuide documentation.
I have installed your software in SYS:Programs/AmiWF instead of SYS:Internet/AmiWF.
Could that be causing the problem?
Would eliminating the search path would solve this?
![Image2](https://github.com/emartisoft/AmiWeatherForecasts/assets/148932062/68df890c-bbff-49df-b9c7-ebb52b36593b)

Problem 3...
An option for using the Visual Prefs palette instead of using the Workbench palette.
When changing themes the palette colour is not always changed just the selection. (see pics)

OS 3.2 Theme...
![Image1](https://github.com/emartisoft/AmiWeatherForecasts/assets/148932062/03bd5cf7-1f8e-446d-a64c-b2e687e77fa5)

IntuitionNG-BW Theme...
![Image2](https://github.com/emartisoft/AmiWeatherForecasts/assets/148932062/e5552246-b5e8-4ab1-b285-7af9dd1abf90)

Visual (GUI) Prefs...
![Image3](https://github.com/emartisoft/AmiWeatherForecasts/assets/148932062/0783e76c-6e84-4ecf-a76e-88410ae39d36)

These are only minor issues, but something I thought might interest you.
Thanks...

**Comment by emartisoft** [comment]
1. This is a standard situation due to changes in System Settings. Sometimes it may be necessary to reboot the system.
2. dopus5 may be changing some settings.
3. Some different applications change the palette settings when they run. I need to change my coding. Let's not prepare a palette that only the application uses. I am working on it.
4. Thank you ;)
