### ISSUE TITLE
mouse problem with amiweatherforecasts opened

### ISSUE THREAD

**Issue by psypoker** [emartisoft/AmiWeatherForecasts#8]
Hi,

when awf was running, i noticed that mouse moving of icons became impossible
without awf running, icon moving is back !
could you confirm that on your config ?

**Comment by emartisoft** [comment]
I think, you can not drag and drop icons on WB. I fixed this. (for V1.4)

**Comment by psypoker** [comment]
nice !
________________________________
De : emarti ***@***.***>
Envoyé : dimanche 26 novembre 2023 14:10
À : emartisoft/AmiWeatherForecasts ***@***.***>
Cc : Sébastien ***@***.***>; Author ***@***.***>
Objet : Re: [emartisoft/AmiWeatherForecasts] mouse problem with amiweatherforecasts opened (Issue #8)


I think, you can not drag and drop icons on WB. I fixed this. (for V1.4)

**Comment by emartisoft** [comment]
Try it for version 1.4
