### ISSUE TITLE
Suggestion: Export weather data to ENV variables 

### ISSUE THREAD

**Issue by bubbob42** [emartisoft/AmiWeatherForecasts#9]
Great tool, thank you!

Please add export of weather data to ENV variable and an optional „no display“ mode. Users could then integrate weather data via 3.2+ WorkbenchPrefs/ConfigureTitlebar using placeholders for these environment variables instead of drawing a window over the screen titlebar. 

This has no side effects. We added the feature for this very purpose (displaying temperature sensor data in my case) ;-)

**Comment by emartisoft** [comment]
Thank you. It's a good idea to keep the variables related to this in **ENV:**. I'll try it for next version.

**Comment by emartisoft** [comment]
Hi again,
Added environment variables (`CurrentTemperature`, `Location `and `WeatherDescription`) for other applications to use.
